### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by HudsonKnott** [u1i/tools#1]
When I try and run the command `ssh -R 80:localhost:80 serveo.net` to tunnel for the webserver I'm hosting it says this: `ssh: connect to host serveo.net port 22: Connection refused`. I tried running `sudo ufw allow 22` to allow the ssh port through the firewall and it still doesn't work. Can anyone help?

**Comment by voccer** [comment]
any help?

**Comment by tvr3000** [comment]
Same problem, did you anyone find a solution? MacOS 11.4 here

**Comment by HudsonKnott** [comment]
I didn't find anything
